name: Release Dev

on:
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  CI: true

jobs:
  release-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: yarn

      - name: Build
        run: |
          yarn changed foreach --parallel --verbose --git-range HEAD~1 run build

      - name: Release
        run: |
          yarn changed foreach --parallel --verbose --git-range HEAD~1 run release

